[package]
name = "tg_anti_spam_bot"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
dotenvy = "0.15.7"
grammers-client = "0.8.1"
grammers-mtsender = "0.8.1"
grammers-session = "0.8.0"
keyring-lib = { version = "1.0.2", features = ["tokio", "rustls"] }
proc-exit = "2.0.2"
tokio = { version = "1.48.0", features = ["macros", "process", "rt-multi-thread", "signal"] }
tokio-util = { version = "0.7.18", features = ["rt"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter", "local-time"] }

[profile.release]
lto = true
strip = "symbols"
